### ISSUE TITLE
 How to load a background image like your home page? And just fit the screen size?

### ISSUE THREAD

**Issue by 97thjingba** [janosh/janosh.io#58]
**How to load a background image like your home page? And just fit the screen size?**
[https://janosh.io/](https://janosh.io/)

**Comment by janosh** [comment]
Hey, take a look at the [`PageTitle`](https://github.com/janosh/janosh.io/blob/master/src/components/PageTitle/index.js) component and how it's used in [`IndexPage`](https://github.com/janosh/janosh.io/blob/master/src/pages/index.js). Basically I'm just using [`gatsby-image`](https://www.gatsbyjs.org/packages/gatsby-image) with a few extra styles applied via [`styled-components`](https://www.styled-components.com):

```js
import Image from "gatsby-image"

export const Img = styled(Image).attrs(
  ({ fluid, src }) => !fluid && { as: src ? `img` : `div` }
)`
  position: absolute !important;
  z-index: -1;
  width: 100%;
  height: 100%;
  background: ${props =>
    props.as === `div` &&
    `linear-gradient(
    28deg,
    rgba(255, 113, 0, 1) 0%,
    rgba(9, 9, 121, 1) 50%,
    rgba(0, 212, 255, 1) 100%
  )`};
  object-fit: cover;
`
```

I'll close this issue for now as it's not really related to this project but feel free to follow up.

**Comment by 97thjingba** [comment]
Thank you for your reply, but I am a beginner and I can't read some code. But thank you very much. 
！！！
