### ISSUE TITLE
Confused user

### ISSUE THREAD

**Issue by theapplegates** [janosh/janosh.io#62]
I am an older man ( 50 ) who is trying to understand coding and Gatsby. I saw your site and I have to say thanks for putting the source code online. I am trying to reverse engineer things but first I wanted to get a copy to run.
 I am having trouble with some things and I wanted to know if you could suggest a fix.
Here is the error I get when I try to post it to Amazon Amplify.

`2020-01-17T16:34:33.192Z [WARNING]: error "gatsby-plugin-mdx" threw an error while running the onCreateNode lifecycle:
                                    JSON5: invalid end of input at 1:1
2020-01-17T16:34:33.220Z [INFO]: [0m
                                 [0m  [0m[97m[41mSyntaxError[0m[37m[41m:[0m[37m[41m [0m[97m[41mJSON5: invalid end of input at 1:1[0m
                                 [0m  [0m
                                 [0m  [0m[90m-[0m [0m[93mparse.js[0m[90m:[0m[93m1083[0m[37m [0m[37msyntaxError[0m
                                 [0m  [0m  [0m[90m[omg-pleasework]/[json5]/lib/parse.js:1083:17[0m
                                 [0m  [0m
                                 [0m  [0m[90m-[0m [0m[93mparse.js[0m[90m:[0m[93m1032[0m[37m [0m[37minvalidEOF[0m
                                 [0m  [0m  [0m[90m[omg-pleasework]/[json5]/lib/parse.js:1032:12[0m
                                 [0m  [0m
                                 [0m  [0m[90m-[0m [0m[93mparse.js[0m[90m:[0m[93m821[0m[37m [0m[37mObject.start[0m
                                 [0m  [0m  [0m[90m[omg-pleasework]/[json5]/lib/parse.js:821:19[0m
                                 [0m  [0m
                                 [0m  [0m[90m-[0m [0m[93mparse.js[0m[90m:[0m[93m32[0m[37m [0m[37mObject.parse[0m
                                 [0m  [0m  [0m[90m[omg-pleasework]/[json5]/lib/parse.js:32:32[0m
                                 [0m  [0m
                                 [0m  [0m[90m-[0m [0m[93mutils.js[0m[90m:[0m[93m78[0m[37m [0m[37mrequireJson[0m
                                 [0m  [0m  [0m[90m[omg-pleasework]/[gatsby-remark-vscode]/src/utils.js:78:71[0m
                                 [0m  [0m
                                 [0m  [0m[90m-[0m [0m[93mprocessExtension.js[0m[90m:[0m[93m6[0m[37m [0m[37mprocessExtension[0m
                                 [0m  [0m  [0m[90m[omg-pleasework]/[gatsby-remark-vscode]/src/processExtension.js:6:23[0m
                                 [0m  [0m
                                 [0m  [0m[90m-[0m [0m[93mdownloadExtension.js[0m[90m:[0m[93m30[0m[37m [0m[37msyncExtensionData[0m
                                 [0m  [0m  [0m[90m[omg-pleasework]/[gatsby-remark-vscode]/src/downloadExtension.js:30:38[0m
                                 [0m  [0m
                                 [0m  [0m[90m-[0m [0m[93mdownloadExtension.js[0m[90m:[0m[93m88[0m[37m [0m[37mdownloadExtensionsIfNeeded[0m
                                 [0m  [0m  [0m[90m[omg-pleasework]/[gatsby-remark-vscode]/src/downloadExtension.js:88:11[0m
                                 [0m  [0m
                                 [0m  [0m[90m-[0m [0m[93mindex.js[0m[90m:[0m[93m77[0m[37m [0m[37masync textmateHighlight[0m
                                 [0m  [0m  [0m[90m[omg-pleasework]/[gatsby-remark-vscode]/src/index.js:77:7[0m
                                 [0m  [0m
                                 [0m  [0m[90m-[0m [0m[93mget-source-plugins-as-remark-plugins.js[0m[90m:[0m[93m57[0m[37m [0m[37masync transformer[0m
                                 [0m  [0m  [0m[90m[omg-pleasework]/[gatsby-plugin-mdx]/utils/get-source-plugins-as-remark-plug[0m  [0m  [0m[90mins.js:57:11[0m
                                 [0m  [0m
                                 [0m
2020-01-17T16:34:33.288Z [INFO]: not finished source and transform nodes - 15.105s
2020-01-17T16:34:33.308Z [INFO]: not finished Generating image thumbnails - 10.986s
2020-01-17T16:34:33.496Z [ERROR]: !!! Build failed
2020-01-17T16:34:33.497Z [ERROR]: !!! Non-Zero Exit Code detected
2020-01-17T16:34:33.497Z [INFO]: # Starting environment caching...
2020-01-17T16:34:33.497Z [INFO]: # Environment caching completed
Terminating logging...`

I can get it to deploy on Netlify only if I remove the 'Gatsby-remark-vscode' code from gatsby-config.js  I was getting an error about Microsoft's rate limit. But as you know the fancy code boxes don't appear if vs-code is removed.

Maybe you can make sense of the error. I appreciate any help you can provide.
Attached is a screenshot because I can't make the code above look good.
Paul
<img width="1557" alt="Screen Shot 2020-01-17 at 11 47 49 AM" src="https://user-images.githubusercontent.com/27178137/72630044-85d01f00-391f-11ea-9163-89c4f046c82b.png">

**Comment by janosh** [comment]
Nice to hear from you, Paul!

The error you're seeing is actually preventing me from redeploying my own site as well. 😞 It's due to Microsoft now blocking an endpoint for downloading VS Code extensions that had only been public by accident in the past. See [here](https://github.com/andrewbranch/gatsby-remark-vscode/issues/69) and [here](https://github.com/andrewbranch/gatsby-remark-vscode/pull/67) for details.

The site should build sucessfully if you checkout the [`grvsc@v2`](https://github.com/janosh/janosh.io/tree/grvsc%40v2) branch or just remove the `extensions` option from `gatsby-remark-vscode` in [`gatsby-config.js`](https://github.com/janosh/janosh.io/blob/master/gatsby-config.js#L17). Also, once @andrewbranch releases v2 of the awesome `gatsby-remark-vscode` everything should be back to working as is.

Let me know if this helped. And all the best with your coding endeavors! 👍

**Comment by theapplegates** [comment]
Thanks, I just checked out your branch, and it looked like by your commit message you just used the alpha version of Andrew's `gatsby-remark-vscode`. Thanks for the help, at least I was not losing my mind, the error looked like Microsoft was limiting things.
